name: Deploy Latest Master

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
      - run: yarn
      - run: yarn lint
      - run: yarn tsc
      - run: yarn test
      - run: yarn deploy-function
        env:
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          GOOGLE_CX_TOKEN: ${{secrets.GOOGLE_CX_TOKEN}}
          GOOGLE_SEARCH_TOKEN: ${{secrets.GOOGLE_SEARCH_TOKEN}}
          OPENWEATHERMAP_TOKEN: ${{secrets.OPENWEATHERMAP_TOKEN}}
          TOKEN: ${{secrets.TOKEN}}
          TRANSLATION_APP_TOKEN: ${{secrets.TRANSLATION_APP_TOKEN}}
          YOUTUBE_TOKEN: ${{secrets.YOUTUBE_TOKEN}}
          FCC_API_KEY: ${{secrets.FCC_API_KEY}}
          FIXER_API_KEY: ${{secrets.FIXER_API_KEY}}
